survos_tabler:
    app:
        code: demo
        title: Tabler Bundle Demo
        description: Slot-driven demo app for Survos Tabler Bundle
        abbr: Tabler <strong>Demo</strong>
        homepage_route: app_homepage
        links:
            github: https://github.com/survos-sites/tabler-bundle
            sponsor: https://github.com/sponsors
    options:
        layout: horizontal
    routes:
        home: app_homepage
        login: app_login
        logout: app_logout
        profile: app_profile
